# This is a basic workflow to help you get started with Actions

name: ReadMe Stats Updater

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Main ReadMe Updater"]
    branches: [master]
    types: 
      - completed
          
jobs:
  UpdateStatsTemplate:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1
      with:
        token: ${{ secrets.USER_TOKEN }}
        template: ./README.md
      # Runs a single command using the runners shell
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "[Automatic] Updated Stats ReadMe.md"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        fi
